apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: flask
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: eu.gcr.io/lbg-cloud-incubation/frontend:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_USER
        - name: MYSQL_PWD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_PWD
        - name: MYSQL_IP
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_IP
        - name: MYSQL_DB
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_DB
        - name: MYSQL_SK
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_SK
